[workspace]
resolver = "2"
members = [
    "crates/rdesktop-core",
    "crates/rdesktop-webview",
    "crates/rdesktop-cef",
    "crates/rdesktop-dev",
    "crates/rdesktop-bundler",
    "crates/rdesktop-cli",
    "examples/hello_world",
    "examples/wallpaper",
    "examples/global_hotkey",
    "examples/input_sim",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/neko233-com/rdesktop"

[workspace.dependencies]
rdesktop-core = { version = "0.1.2", path = "crates/rdesktop-core" }
rdesktop-webview = { version = "0.1.2", path = "crates/rdesktop-webview" }
rdesktop-cef = { version = "0.1.2", path = "crates/rdesktop-cef" }
rdesktop-dev = { version = "0.1.2", path = "crates/rdesktop-dev" }
rdesktop-bundler = { version = "0.1.2", path = "crates/rdesktop-bundler" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
tao = "0.36"
